name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: macos-12

    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3
      #- name: Select Xcode
      #  run: sudo xcode-select -switch /Applications/Xcode_14.0.app

      # Runs a set of commands using the runners shell
      #- name: Xcode version
      #  run: /usr/bin/xcodebuild -version
      - name: Build and test
        run: xcodebuild clean build test -project EssentialFeed/EssentialFeed.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

